// <auto-generated />
using System;
using BusinessSchedulingApplication.Server.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessSchedulingApplication.Server.Migrations
{
    [DbContext(typeof(BusinessSchedulingApplicationContext))]
    partial class BusinessSchedulingApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessSchedulingApplication.Server.Models.AppUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("UTC");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("UserId");

                    b.HasIndex(new[] { "Email" }, "IX_AppUsers_Email")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("BusinessSchedulingApplication.Server.Models.Appointment", b =>
                {
                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedVia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ScheduledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("AppointmentId");

                    b.HasIndex(new[] { "CreatedByUserId" }, "IX_Appointments_CreatedByUserId");

                    b.HasIndex(new[] { "CustomerId", "ScheduledAtUtc" }, "IX_Appointments_CustomerId_ScheduledAtUtc");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("BusinessSchedulingApplication.Server.Models.BusinessHour", b =>
                {
                    b.Property<Guid>("BusinessHourId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly?>("ClosesAtUtc")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<TimeOnly?>("OpensAtUtc")
                        .HasColumnType("time");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("BusinessHourId");

                    b.HasIndex(new[] { "OwnerUserId" }, "IX_BusinessHours_OwnerUserId");

                    b.HasIndex(new[] { "OwnerUserId", "DayOfWeek" }, "IX_BusinessHours_OwnerUserId_DayOfWeek")
                        .IsUnique();

                    b.ToTable("BusinessHours");
                });

            modelBuilder.Entity("BusinessSchedulingApplication.Server.Models.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("CustomerId");

                    b.HasIndex(new[] { "FullName" }, "IX_Customers_FullName");

                    b.HasIndex(new[] { "PhoneNumber" }, "IX_Customers_PhoneNumber")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("BusinessSchedulingApplication.Server.Models.SmsConversation", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastMessageAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UnreadCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("ConversationId");

                    b.HasIndex(new[] { "CustomerId" }, "IX_SmsConversations_CustomerId")
                        .IsUnique();

                    b.ToTable("SmsConversations");
                });

            modelBuilder.Entity("BusinessSchedulingApplication.Server.Models.SmsMessage", b =>
                {
                    b.Property<Guid>("SmsMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MessageBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("SmsMessageId");

                    b.HasIndex(new[] { "ConversationId", "SentAtUtc" }, "IX_SmsMessages_ConversationId_SentAtUtc");

                    b.HasIndex(new[] { "CustomerId" }, "IX_SmsMessages_CustomerId");

                    b.ToTable("SmsMessages");
                });

            modelBuilder.Entity("BusinessSchedulingApplication.Server.Models.Appointment", b =>
                {
                    b.HasOne("BusinessSchedulingApplication.Server.Models.AppUser", "CreatedByUser")
                        .WithMany("Appointments")
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("BusinessSchedulingApplication.Server.Models.Customer", "Customer")
                        .WithMany("Appointments")
                        .HasForeignKey("CustomerId")
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BusinessSchedulingApplication.Server.Models.BusinessHour", b =>
                {
                    b.HasOne("BusinessSchedulingApplication.Server.Models.AppUser", "OwnerUser")
                        .WithMany("BusinessHours")
                        .HasForeignKey("OwnerUserId")
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("BusinessSchedulingApplication.Server.Models.Customer", b =>
                {
                });

            modelBuilder.Entity("BusinessSchedulingApplication.Server.Models.SmsConversation", b =>
                {
                    b.HasOne("BusinessSchedulingApplication.Server.Models.Customer", "Customer")
                        .WithOne("SmsConversation")
                        .HasForeignKey("BusinessSchedulingApplication.Server.Models.SmsConversation", "CustomerId")
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BusinessSchedulingApplication.Server.Models.SmsMessage", b =>
                {
                    b.HasOne("BusinessSchedulingApplication.Server.Models.SmsConversation", "Conversation")
                        .WithMany("SmsMessages")
                        .HasForeignKey("ConversationId")
                        .IsRequired();

                    b.HasOne("BusinessSchedulingApplication.Server.Models.Customer", "Customer")
                        .WithMany("SmsMessages")
                        .HasForeignKey("CustomerId")
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BusinessSchedulingApplication.Server.Models.AppUser", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("BusinessHours");

                    b.Navigation("CustomerOwnerships");
                });

            modelBuilder.Entity("BusinessSchedulingApplication.Server.Models.Customer", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("SmsConversation");

                    b.Navigation("SmsMessages");
                });

            modelBuilder.Entity("BusinessSchedulingApplication.Server.Models.SmsConversation", b =>
                {
                    b.Navigation("SmsMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
